# [LAB 08] 1. EDA 시작하기
## #01. 준비작업
### 1. 라이브러리 참조

In [1]:
from hossam import load_data
from helpers import *

📦 아이티윌 이광호 강사가 제작한 라이브러리를 사용중입니다.
📚 자세한 사용 방법은 https://py.hossam.kr 을 참고하세요.
📧 Email: leekh4232@gmail.com
🎬 Youtube: https://www.youtube.com/@hossam-codingclub
📝 Blog: https://blog.hossam.kr/
🔖 Version: 0.5.19

### 2. 품질점검 완료 데이터 가져오기
- lab-05에서 가져온 데이터 셋을 불러온다

In [2]:
origin = load_data('boston_qtcheck')
origin.head()

📚 보스턴 주택 가격 데이터셋의 품질 검사 완료 버전 (출처: 자체 정제)

    field    description
--  -------  ---------------------------------------------------------------------------------------------
 0  CRIM     타운별 1인당 범죄율 (Per capita crime rate by town)
 1  ZN       25,000 sqft 이상 주거용 대지 비율 (Proportion of residential land zoned for large lots)
 2  INDUS    비소매 상업구역 비율 (Proportion of non-retail business acres per town)
 3  CHAS     명목형, 찰스강 인접 여부 (Charles River dummy variable: 1 if tract bounds river; 0 otherwise)
 4  NOX      대기 오염 정도 (Nitric oxides concentration, parts per 10 million)
 5  RM       주택당 평균 방(Room) 수 (Average number of rooms per dwelling)
 6  AGE      1940년 이전 건축 비율 (Proportion of owner-occupied units built prior to 1940)
 7  DIS      5개 주요 고용센터까지의 거리 (Weighted distances to five Boston employment centers)
 8  RAD      고속도로 접근성 지수 (Index of accessibility to radial highways)
 9  TAX      재산세율 (Full-value property-tax rate per $10,000)
10  PTRATIO  교육구 학생-교사 비율 (Pupil–teacher ratio by town)
11  B        흑인 비율 지수 (1000(Bk − 0.63)²; Bk = proportion of Black residents)
12  LSTAT    저소득층 비율 (%) (Percentage of lower status population)
13  MEDV     주택 가격 중앙값(단위: $1,000) (Median value of owner-occupied homes in $1000s)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.006,18.000,2.310,0,0.538,6.575,65.200,4.090,1,296,15.300,396.900,4.980,24.000
1,0.027,0.000,7.070,0,0.469,6.421,78.900,4.967,2,242,17.800,396.900,9.140,21.600
2,0.027,0.000,7.070,0,0.469,7.185,61.100,4.967,2,242,17.800,392.830,4.030,34.700
3,0.032,0.000,2.180,0,0.458,6.998,45.800,6.062,3,222,18.700,394.630,2.940,33.400
4,0.069,0.000,2.180,0,0.458,7.147,54.200,6.062,3,222,18.700,396.900,5.330,36.200

### 3. 연속형 변수의 기초 통계량 가져오기
- lab-05에서 저장해 둔 기초 통계량 표를 불러온다.
    - 실제 데이터 분석 프로젝트에서는 엑셀 파일로 저장해두고 필요할때마다 열람하자.

In [3]:
desc = load_data('boston_qtcheck_desc')
desc.T

📚 보스턴 주택 가격 데이터셋의 품질 검사 완료 버전에 대한 기술통계량 표

,CRIM,ZN,INDUS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
count,506.000,506.000,506.000,506.000,506.000,506.000,506.000,506.000,506.000,506.000,506.000,506.000,506.000
mean,3.614,11.364,11.137,0.555,6.285,68.575,3.795,9.549,408.237,18.456,356.674,12.653,22.533
std,8.602,23.322,6.860,0.116,0.703,28.149,2.106,8.707,168.537,2.165,91.295,7.141,9.197
min,0.006,0.000,0.460,0.385,3.561,2.900,1.130,1.000,187.000,12.600,0.320,1.730,5.000
25%,0.082,0.000,5.190,0.449,5.885,45.025,2.100,4.000,279.000,17.400,375.377,6.950,17.025
50%,0.257,0.000,9.690,0.538,6.208,77.500,3.207,5.000,330.000,19.050,391.440,11.360,21.200
75%,3.677,12.500,18.100,0.624,6.623,94.075,5.188,24.000,666.000,20.200,396.225,16.955,25.000
max,88.976,100.000,27.740,0.871,8.780,100.000,12.127,24.000,711.000,22.000,396.900,37.970,50.000
rel_diff,13.087,inf,0.149,0.031,0.012,0.115,0.183,0.910,0.237,0.031,0.089,0.114,0.063
rdiff_flag,large_diff,large_diff,diff,similar,similar,diff,diff,large_diff,diff,similar,similar,diff,similar
iqr,3.595,12.500,12.910,0.175,0.738,49.050,3.088,20.000,387.000,2.800,20.848,10.005,7.975
upper_bound,9.070,31.250,37.465,0.886,7.731,167.650,9.821,54.000,1246.500,24.400,427.496,31.963,36.963
lower_bound,-5.311,-18.750,-14.175,0.187,4.778,-28.550,-2.532,-26.000,-301.500,13.200,344.106,-8.058,5.062
upper_outliers,66,68,0,0,22,0,5,0,0,0,0,7,38
upper_outliers_ratio,0.130,0.134,0.000,0.000,0.043,0.000,0.010,0.000,0.000,0.000,0.000,0.014,0.075
lower_outliers,0,0,0,0,8,0,0,0,0,15,77,0,2
lower_outliers_ratio,0.000,0.000,0.000,0.000,0.016,0.000,0.000,0.000,0.000,0.030,0.152,0.000,0.004
outliers,66,68,0,0,30,0,5,0,0,15,77,7,40
outliers_ratio,0.130,0.134,0.000,0.000,0.059,0.000,0.010,0.000,0.000,0.030,0.152,0.014,0.079
skew,5.223,2.226,0.295,0.729,0.404,-0.599,1.012,1.005,0.670,-0.802,-2.890,0.906,1.108
skew_interpret,right tail,right tail,symmetric,right tail,symmetric,left tail,right tail,right tail,right tail,left tail,left tail,right tail,right tail
kurt,37.131,4.032,-1.234,-0.065,1.892,-0.968,0.488,-0.867,-1.142,-0.285,7.227,0.493,1.495
kurt_interpret,leptokurtic,leptokurtic,platykurtic,platykurtic,leptokurtic,platykurtic,leptokurtic,platykurtic,platykurtic,platykurtic,leptokurtic,leptokurtic,leptokurtic
log_need,log1p,log1p,none,none,none,none,log1p,log1p,none,none,reverse_log1p,log1p,log1p

### 4. 명목형 변수의 기초 통계량 가져오기
- LAB-05에서 저장해둔 기초 통계량 표를 불러온다.
    - 실제 데이터 분석 프로젝트에서는 엑셀 파일로 저장해두고 필요할때마다 열람하자.

In [4]:
cat_desc = load_data('boston_qtcheck_category_desc')
cat_desc

📚 보스턴 주택 가격 데이터셋의 품질 검사 완료 버전에 대한 범주형 변수 기술통계량 표

        CHAS
count    506
unique     2
top        0
freq     471

- 분포 : 명목형 변수 중 유일한 이항 변수이며, 심한 불균형
- 분석 시 유의점
    - 두 집단에 대한 비교인 T검정을 쓰되, 표본 불균형으로 검정력이 낮아질 수 있음에 유의
    - 모델 투입시 한쪽 범주(소수집단)의 영향이 과소, 과대 추정될 수 있어 해석에 주의
- 활용 : 소수집단이라도 강변 인접이 가격에 유의미한 프리미엄을 주는지 확인하면 해석가치가 큰 변수가 될 수 있음(버리지 말고 검정으로 확인)

### 5. 타입변환(명목형 확정)
- 명목형 기술 통계량 표에 의하면 명목형 변수는 CHAS 하나이다.

In [5]:
df = my_qtcheck.set_type(origin, as_category=['CHAS'])

<class 'pandas.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    category
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64
 9   TAX      506 non-null    int64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: category(1), float64(11), int64(2)
memory usage: 52.0 KB