# [LAB 10] 1. 분석용 데이터 전처리
## #연습문제

In [1]:
from hossam import load_data
from helpers import *

📦 아이티윌 이광호 강사가 제작한 라이브러리를 사용중입니다.
📚 자세한 사용 방법은 https://py.hossam.kr 을 참고하세요.
📧 Email: leekh4232@gmail.com
🎬 Youtube: https://www.youtube.com/@hossam-codingclub
📝 Blog: https://blog.hossam.kr/
🔖 Version: 0.5.21

⚠️  'hossam' 패키지의 최신 버전이 출시되었습니다! (설치된 버전: 0.5.21, 최신 버전: 0.5.23)
   최신 버전으로 업데이트하려면 다음 명령어를 실행하세요:
   pip install --upgrade hossam

In [2]:
origin = load_data('insurance_qtcheck')
origin.head()

📚 보험 비용 데이터셋의 품질 검사 완료 버전 (출처: 자체 정제)

   age     sex    bmi  children smoker     region   charges
0   19  female 27.900         0    yes  southwest 16884.924
1   18    male 33.770         1     no  southeast  1725.552
2   28    male 33.000         3     no  southeast  4449.462
3   33    male 22.705         0     no  northwest 21984.471
4   32    male 28.880         0     no  northwest  3866.855

In [3]:
desc = load_data('insurance_qtcheck_desc')
desc.T

📚 보험 비용 데이터셋의 연속형 변수에 대한 기술 통계량 (출처: 자체 작업)

                              age          bmi     children      charges
count                    1337.000     1337.000     1337.000     1337.000
mean                       39.222       30.663        1.096    13279.121
std                        14.044        6.100        1.206    12110.360
min                        18.000       15.960        0.000     1121.874
25%                        27.000       26.290        0.000     4746.344
50%                        39.000       30.400        1.000     9386.161
75%                        51.000       34.700        2.000    16657.717
max                        64.000       53.130        5.000    63770.428
rel_diff                    0.006        0.009        0.096        0.415
rdiff_flag                similar      similar      similar         diff
iqr                        24.000        8.410        2.000    11911.373
upper_bound                87.000       47.315        5.000    34524.778
lower_bound                -9.000       13.675       -3.000   -13120.716
upper_outliers                  0            9            0          139
upper_outliers_ratio        0.000        0.007        0.000        0.104
lower_outliers                  0            0            0            0
lower_outliers_ratio        0.000        0.000        0.000        0.000
outliers                        0            9            0          139
outliers_ratio              0.000        0.007        0.000        0.104
skew                        0.055        0.284        0.937        1.515
skew_interpret          symmetric    symmetric   right tail   right tail
kurt                       -1.244       -0.053        0.201        1.604
kurt_interpret        platykurtic  platykurtic  leptokurtic  leptokurtic
log_need                     none         none        log1p        log1p

In [4]:
cat_desc = load_data('insurance_qtcheck_category_desc')
cat_desc

📚 보험 비용 데이터셋의 범주형 변수에 대한 기술 통계량 (출처: 자체 작업)

  Unnamed: 0   sex smoker     region
0      count  1337   1337       1337
1     unique     2      2          4
2        top  male     no  southeast
3       freq   675   1063        364

In [5]:
df = my_qtcheck.set_type(origin, as_category=['sex', 'smoker', 'region'])

<class 'pandas.DataFrame'>
RangeIndex: 1337 entries, 0 to 1336
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1337 non-null   int64
 1   sex       1337 non-null   category
 2   bmi       1337 non-null   float64
 3   children  1337 non-null   int64
 4   smoker    1337 non-null   category
 5   region    1337 non-null   category
 6   charges   1337 non-null   float64
dtypes: category(3), float64(2), int64(2)
memory usage: 46.0 KB

In [6]:
# 종속변수 이름
target = "charges"
# 명목형 변수 이름
nominal_cols = my_qtcheck.get_categorical_column_names(df)
# 연속형(종속변수 포함)
continuous_cols = my_qtcheck.get_number_column_names(df)
# 연속형 독립변수
feature_continuous= [c for c in continuous_cols if c != target]

In [7]:
print("목표변수:", target)
print("연속형(종속변수 포함) :", continuous_cols)
print("독립변수(명목형) :", nominal_cols)
print("독립변수(연속형) :", feature_continuous)

display(df.head())
display(desc)
display(cat_desc)

목표변수: charges
연속형(종속변수 포함) : ['age', 'bmi', 'children', 'charges']
독립변수(명목형) : ['sex', 'smoker', 'region']
독립변수(연속형) : ['age', 'bmi', 'children']

   age     sex    bmi  children smoker     region   charges
0   19  female 27.900         0    yes  southwest 16884.924
1   18    male 33.770         1     no  southeast  1725.552
2   28    male 33.000         3     no  southeast  4449.462
3   33    male 22.705         0     no  northwest 21984.471
4   32    male 28.880         0     no  northwest  3866.855

,count,mean,std,min,25%,50%,75%,max,rel_diff,rdiff_flag,iqr,upper_bound,lower_bound,upper_outliers,upper_outliers_ratio,lower_outliers,lower_outliers_ratio,outliers,outliers_ratio,skew,skew_interpret,kurt,kurt_interpret,log_need
age,1337.000,39.222,14.044,18.000,27.000,39.000,51.000,64.000,0.006,similar,24.000,87.000,-9.000,0,0.000,0,0.000,0,0.000,0.055,symmetric,-1.244,platykurtic,none
bmi,1337.000,30.663,6.100,15.960,26.290,30.400,34.700,53.130,0.009,similar,8.410,47.315,13.675,9,0.007,0,0.000,9,0.007,0.284,symmetric,-0.053,platykurtic,none
children,1337.000,1.096,1.206,0.000,0.000,1.000,2.000,5.000,0.096,similar,2.000,5.000,-3.000,0,0.000,0,0.000,0,0.000,0.937,right tail,0.201,leptokurtic,log1p
charges,1337.000,13279.121,12110.360,1121.874,4746.344,9386.161,16657.717,63770.428,0.415,diff,11911.373,34524.778,-13120.716,139,0.104,0,0.000,139,0.104,1.515,right tail,1.604,leptokurtic,log1p

  Unnamed: 0   sex smoker     region
0      count  1337   1337       1337
1     unique     2      2          4
2        top  male     no  southeast
3       freq   675   1063        364

In [8]:
df1 = my_prep.labeling(df, columns=nominal_cols)
df1.head()

sex (2종): female=0, male=1
smoker (2종): no=0, yes=1
region (4종): northeast=0, northwest=1, southeast=2, southwest=3

   age  sex    bmi  children  smoker  region   charges
0   19    0 27.900         0       1       3 16884.924
1   18    1 33.770         1       0       2  1725.552
2   28    1 33.000         3       0       2  4449.462
3   33    1 22.705         0       0       1 21984.471
4   32    1 28.880         0       0       1  3866.855

In [9]:
df2 = my_prep.dummies(df1, columns=nominal_cols, drop_first=True)
df2.to_excel("10.연습문제_체크포인트0_기준선.xlsx", index=False)
df2.head()

region (4종) -> 3개: region_1, region_2, region_3 (기준: 0 제외)
sex (2종) -> 생략: 이진 변수이므로 원래 컬럼을 유지
smoker (2종) -> 생략: 이진 변수이므로 원래 컬럼을 유지

컬럼 수: 7개 -> 9개

   age  sex    bmi  children  smoker   charges  region_1  region_2  region_3
0   19    0 27.900         0       1 16884.924         0         0         1
1   18    1 33.770         1       0  1725.552         0         1         0
2   28    1 33.000         3       0  4449.462         0         1         0
3   33    1 22.705         0       0 21984.471         1         0         0
4   32    1 28.880         0       0  3866.855         1         0         0

In [10]:
# 우측꼬리 로그 변환 대상 컬럼
log_cols = desc.loc[desc['log_need']=='log1p'].index.tolist()
log_cols

['children', 'charges']

In [12]:
df3 = my_prep.log_transform(df2, log_columns=log_cols, reflect_columns=reflect_cols)
df3.to_excel("10.연습문제_체크포인트1_로그변환.xlsx", index=False)
df3.head()

컬럼        꼬리방향      변환식                   역변환식                                  왜도
----------------------------------------------------------------------------------------
children  우측 꼬리     log(1+x)              exp(y)-1                0.94 -> 0.26
charges   우측 꼬리     log(1+x)              exp(y)-1                1.51 -> -0.09

   age  sex    bmi  children  smoker  charges  region_1  region_2  region_3
0   19    0 27.900     0.000       1    9.734         0         0         1
1   18    1 33.770     0.693       0    7.454         0         1         0
2   28    1 33.000     1.386       0    8.401         0         1         0
3   33    1 22.705     0.000       0    9.998         1         0         0
4   32    1 28.880     0.000       0    8.260         1         0         0

In [13]:
df4 = my_prep.replace_outlier(df3, columns=feature_continuous)
df4.to_excel("10.연습문제_체크포인트2_이상치대체.xlsx", index=False)
df4.head()

이상치 대체 방식: 'bound' (기준: IQR x 1.5)
컬럼                               정상 범위       이상치                   대체값
--------------------------------------------------------------------
age                    -9.00 ~ 87.00    0개(0.0%)      -9.00 또는 87.00
bmi                    13.67 ~ 47.32    9개(0.7%)      13.67 또는 47.32
children                -1.65 ~ 2.75    0개(0.0%)       -1.65 또는 2.75

   age  sex    bmi  children  smoker  charges  region_1  region_2  region_3
0   19    0 27.900     0.000       1    9.734         0         0         1
1   18    1 33.770     0.693       0    7.454         0         1         0
2   28    1 33.000     1.386       0    8.401         0         1         0
3   33    1 22.705     0.000       0    9.998         1         0         0
4   32    1 28.880     0.000       0    8.260         1         0         0

In [14]:
df5 = my_prep.reduce_vif(df4, columns=feature_continuous, threshold=10.0)
df5.to_excel("10.연습문제_체크포인트3_다중공선성제거.xlsx", index=False)
df5.head()

완료! 남은 변수: ['age', 'bmi', 'children']
최대 VIF = 1.01

   age  sex    bmi  children  smoker  charges  region_1  region_2  region_3
0   19    0 27.900     0.000       1    9.734         0         0         1
1   18    1 33.770     0.693       0    7.454         0         1         0
2   28    1 33.000     1.386       0    8.401         0         1         0
3   33    1 22.705     0.000       0    9.998         1         0         0
4   32    1 28.880     0.000       0    8.260         1         0         0

In [15]:
df6 = my_prep.scaling(df5, columns=feature_continuous, method='standard')
df6.to_excel("10.연습문제_체크포인트4_정규화.xlsx", index=False)
df6.head()

StandardScaler 적용 (3개 컬럼)
컬럼                            변환 전                  변환 후
--------------------------------------------------------
age                18.00 ~ 64.00          -1.51 ~ 1.76
bmi                15.96 ~ 47.32          -2.43 ~ 2.75
children             0.00 ~ 1.79          -1.04 ~ 2.17

     age  sex    bmi  children  smoker  charges  region_1  region_2  region_3
0 -1.440    0 -0.454    -1.043       1    9.734         0         0         1
1 -1.512    1  0.515     0.199       0    7.454         0         1         0
2 -0.799    1  0.388     1.441       0    8.401         0         1         0
3 -0.443    1 -1.312    -1.043       0    9.998         1         0         0
4 -0.514    1 -0.292    -1.043       0    8.260         1         0         0